var Dinner = ["Engr Ali Mirza", " Sir Sahil Adeem", "Moulana Syed Moududi"];
Dinner.push("Syed Qutub");
Dinner.push("Adolf Hotler");
Dinner.push("Allama Iqbal");
Dinner.push("Mohammad Ali Jinnah");
var Message = " would you mind Joining me for Dinner Tonight ? ";
console.log(Dinner[0], Message);
console.log(Dinner[1], Message);
console.log(Dinner[2], Message);
console.log(Dinner[3], Message);
console.log(Dinner[4], Message);
console.log(Dinner[5], Message);
console.log(Dinner[6], Message);
